#!/usr/bin/env python3
"""
Generate include/sjis_table.h from official CP932 mapping file.

- ダウンロード先: Unicode Consortium (PUBLIC/MAPPINGS/OBSOLETE/EASTASIA/OTHERS/CP932.TXT)
- 出力先       : include/sjis_table.h
  * sjis_pair_t { uint16_t sjis; uint32_t uni; } の配列
  * バイナリ検索用に SJIS 昇順でソート

実行例:
    $ python scripts/gen_sjis_table.py
"""

from __future__ import annotations
from pathlib import Path
import argparse
import re
import ssl
import urllib.request

CP932_URLS = (
    # 新しい正式パス
    "https://ftp.unicode.org/Public/MAPPINGS/VENDORS/MICSFT/WINDOWS/CP932.TXT",
    # 旧パス（念のため残す）
    "https://ftp.unicode.org/Public/MAPPINGS/OBSOLETE/EASTASIA/OTHERS/CP932.TXT",
)

HEADER_TEMPLATE = """\
/* Auto‑generated by gen_sjis_table.py — DO NOT EDIT */
#pragma once
#include <stdint.h>

typedef struct {{ uint16_t sjis; uint32_t uni; }} sjis_pair_t;
static const sjis_pair_t SJIS_MAP[{size}] = {{
{rows}
}};
"""


def download_cp932(urls: list[str]) -> str:
    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE

    last_err: Exception | None = None
    for url in urls:
        try:
            with urllib.request.urlopen(url, context=ctx) as resp:
                return resp.read().decode("ascii", "replace")
        except Exception as e:           # 404 / network error
            print(f"  ‑ {url.split('/')[-2]} ... failed ({e})")
            last_err = e
    raise last_err or RuntimeError("No URL succeeded")


def parse_pairs(text: str) -> list[tuple[int, int]]:
    """Parse lines like '0x8140  0x3000 # ...' or '0xA1  0xFF61 # ...'
    
    Handles both 2-digit (half-width katakana, ASCII) and 4-digit SJIS codes.
    """
    # Match 2-4 digit SJIS codes and 4 digit Unicode codes
    pat = re.compile(r"^0x([0-9A-F]{2,4})\s+0x([0-9A-F]{4})", re.IGNORECASE)
    pairs: list[tuple[int, int]] = []
    for line in text.splitlines():
        m = pat.match(line)
        if m:
            sj, uni = int(m[1], 16), int(m[2], 16)
            pairs.append((sj, uni))
    pairs.sort(key=lambda t: t[0])           # SJIS 昇順
    return pairs


def emit_header(pairs: list[tuple[int, int]]) -> str:
    row_lines = [
        f"  {{0x{sj:04X}, 0x{uni:04X}}},"
        for sj, uni in pairs
    ]
    return HEADER_TEMPLATE.format(size=len(pairs), rows="\n".join(row_lines))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "-o", "--output",
        default=str(Path(__file__).resolve().parents[1] / "include" / "sjis_table.h"),
        help="output header path (default: include/sjis_table.h)",
    )
    args = parser.parse_args()

    print("Downloading CP932.TXT ...")
    text = download_cp932(CP932_URLS)
    print("Parsing ...")
    pairs = parse_pairs(text)
    hdr = emit_header(pairs)

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(hdr, encoding="utf-8")
    print(f"Wrote {out_path} ({len(pairs)} entries).")


if __name__ == "__main__":
    main()
